#!/bin/sh
#To check the battery via terminal
#Use the /sys interface

#cat /sys/class/power_supply/BAT1/uevent
# just because not every manufacturer uses BAT1 for the primary battery.

bat_addr=`ls /sys/class/power_supply | grep "BAT"`

# Well I dont want to see the manufacturer of the battery. I just want to check the remaining power left.
out_full=`cat /sys/class/power_supply/$bat_addr/uevent | grep "POWER_SUPPLY_CHARGE_FULL="`
out_now=`cat /sys/class/power_supply/$bat_addr/uevent | grep "POWER_SUPPLY_CHARGE_NOW"`
echo $out_full
echo $out_now
